# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0124156f3f4cf635429f01737fc6411492b2d309506071c8ce644a5ff08c596ba4bcf182ad54b131f9ab7f91659dc69e53d693c5d033c338055be8aee7da6e28

test:
  secret_key_base: e151cef27075a36f413c8444b4ac26aaba87eb9a22f79f76cf1379b169b46b48808a1ea92c8b8b31bd66bf25bd59f942075c8d3915aa3532dad0e6084e8fb300

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
